///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mathematics
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MathematicsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("bb702d5b-7f83-4046-b41a-76ccb7de2beb")]
    public partial class MathematicsRepository : RepoGenBaseFolder
    {
        static MathematicsRepository instance = new MathematicsRepository();
        MathematicsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the MathematicsRepository element repository.
        /// </summary>
        [RepositoryFolder("bb702d5b-7f83-4046-b41a-76ccb7de2beb")]
        public static MathematicsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MathematicsRepository() 
            : base("MathematicsRepository", "/", null, 0, false, "bb702d5b-7f83-4046-b41a-76ccb7de2beb", ".\\RepositoryImages\\MathematicsRepositorybb702d5b.rximgres")
        {
            _snapxuntitled = new MathematicsRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bb702d5b-7f83-4046-b41a-76ccb7de2beb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("4adb4bb9-9f89-49fe-adf8-806d61028b9e")]
        public virtual MathematicsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class MathematicsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("4adb4bb9-9f89-49fe-adf8-806d61028b9e")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _finishInfo;
            RepoItemInfo _textmeasureInfo;
            RepoItemInfo _switchtosensorInfo;
            RepoItemInfo _buttongoInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "4adb4bb9-9f89-49fe-adf8-806d61028b9e", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 600000, null, "e4526397-d53e-4bd4-b99a-0448a7b0f99c");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@controlid='59648']/form//button[@text='&OK']", 600000, null, "a6cf9ea9-87f7-4d8e-a044-66466c3c75b6");
                _finishInfo = new RepoItemInfo(this, "Finish", "container[@controlid='59648']/form//button[@text='Finish' and @enabled='True']", 600000, null, "1c3ae803-71b0-40e2-a80d-53f3f1a9132e");
                _textmeasureInfo = new RepoItemInfo(this, "TextMeasure", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='2394']", 30000, null, "86972a5c-8b90-4976-9b07-a7b4ff1b579f");
                _switchtosensorInfo = new RepoItemInfo(this, "SwitchToSensor", "container[@controlid='59648']/form[@title='Untitled']/?/?/element[@controlid='59650']/element[@controlid='59648']/toolbar[@controlid='59392']/button[@commandid='40029']", 30000, null, "9a08a71a-aceb-47d2-8300-f2f28bfab3c0");
                _buttongoInfo = new RepoItemInfo(this, "ButtonGo", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']/button[@text='Go']", 100000, null, "6963d63d-3dcc-4493-92ac-8da6d4cba747");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4adb4bb9-9f89-49fe-adf8-806d61028b9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4adb4bb9-9f89-49fe-adf8-806d61028b9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("e4526397-d53e-4bd4-b99a-0448a7b0f99c")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("e4526397-d53e-4bd4-b99a-0448a7b0f99c")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a6cf9ea9-87f7-4d8e-a044-66466c3c75b6")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a6cf9ea9-87f7-4d8e-a044-66466c3c75b6")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("1c3ae803-71b0-40e2-a80d-53f3f1a9132e")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("1c3ae803-71b0-40e2-a80d-53f3f1a9132e")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The TextMeasure item.
            /// </summary>
            [RepositoryItem("86972a5c-8b90-4976-9b07-a7b4ff1b579f")]
            public virtual Ranorex.Text TextMeasure
            {
                get
                {
                    return _textmeasureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMeasure item info.
            /// </summary>
            [RepositoryItemInfo("86972a5c-8b90-4976-9b07-a7b4ff1b579f")]
            public virtual RepoItemInfo TextMeasureInfo
            {
                get
                {
                    return _textmeasureInfo;
                }
            }

            /// <summary>
            /// The SwitchToSensor item.
            /// </summary>
            [RepositoryItem("9a08a71a-aceb-47d2-8300-f2f28bfab3c0")]
            public virtual Ranorex.Button SwitchToSensor
            {
                get
                {
                    return _switchtosensorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToSensor item info.
            /// </summary>
            [RepositoryItemInfo("9a08a71a-aceb-47d2-8300-f2f28bfab3c0")]
            public virtual RepoItemInfo SwitchToSensorInfo
            {
                get
                {
                    return _switchtosensorInfo;
                }
            }

            [RepositoryItem("6963d63d-3dcc-4493-92ac-8da6d4cba747")]
            public virtual Ranorex.Button ButtonGo
            {
                get
                {
                    return _buttongoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonGo item info.
            /// </summary>
            [RepositoryItemInfo("6963d63d-3dcc-4493-92ac-8da6d4cba747")]
            public virtual RepoItemInfo ButtonGoInfo
            {
                get
                {
                    return _buttongoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}